### ISSUE TITLE
search box file

### ISSUE THREAD

**Issue by 439bananas** [coke11/NFE#1]
You actually need the file extension for a file on here. e.g. if you're creating a file in PHP and its name is main, the name of the file should actually be main.php

EDIT: A variable in JS should look like this: var VARIABLENAME = VALUE

**Comment by coke11** [comment]
Alright thanks. I was just copying a pasting some code and messing around with it trying to see what I could do. Wasn't using tutorials or anything. I will be sure to use your advice!
